### ISSUE TITLE
Conflict-based backjumping?

### ISSUE THREAD

**Issue by nornagon** [chocoteam/choco-graph#12]
I tried using the LearnCBJ learner in choco-solver, but it seemed to choke on graph variables. Would it make sense to adapt the CBJ implementation in choco-solver to support graph variables, or is that a PhD thesis? :)

**Comment by jgFages** [comment]
There is actually already a few PhD thesis on the topic! I am afraid it would be quite time consuming.  May I ask in which context are you looking for it? There may be another way to leverage performances of the solver.

**Comment by nornagon** [comment]
I'm using choco-solver to generate maps for a video game, and using choco-graph to ensure that every room in the map is reachable (using the `nbConnectedComponents` constraint). It's quite performant on the particular maps I'm generating at the moment, but I'm worried that with more difficult constraints (such as a more limited tileset or requirements on minimum numbers of certain features) it will get stuck. I'm by no means an expert in CP theory, but I was thinking it would be helpful if choco-graph could generate an explanation of decisions that caused the `nbConnectedComponents` constraint to fail and backjump to those decisions. Perhaps I'm off the trail there though :)

**Comment by jgFages** [comment]
It could be an option but i would suggest to wait the problem to occur before worrying (and generate larger test data to wait in a more proactive way) 😉 if the problem arises, they would presumably be various improvement perspective, including cbj but not only

**Comment by cprudhom** [comment]
Adapting CBJ (or any explanation based approach) may not be adapted so easily to set variables and graph variables. 
1. it requires to change the way modification events are stored in the implication graph needed to compute backtrack-point (or more generally explanations). Indeed, for now, at most 3 ints are required to encode an event on integer variable, where list of ints would be required for sets. 
2. it also requires to create a default explanation schema for set-based constraints / graph-based constraints. Even more challenging and required for efficiency purpose, to develop *ad-hoc* explanation algorithm for wide-spread constraints.

Any of those points are manageable, but they are not straightforward.

One way around this would be to generate some simple clauses on failure, only based on some constraint-local deductions (something like [Deriving filtering algorithms from dedicated
algorithms: zoom on the Bin Packing problem](https://www.archives-ouvertes.fr/hal-01312527/document)) 

My two cents.
