### ISSUE TITLE
Choco-graph with Choco3 version 3.3.2

### ISSUE THREAD

**Issue by ezulkosk** [chocoteam/choco-graph#5]
I am trying to use choco-graph with version 3.3.2 of choco3, and am running into the following compile errors. Can this please be looked into?

[ERROR] diagnostic: /home/ezulkosk/idea/choco-graph-fork/src/main/java/org/chocosolver/solver/variables/GraphVar.java:36: error: cannot find symbol
import org.chocosolver.solver.explanations.VariableState;
                                          ^
  symbol:   class VariableState
  location: package org.chocosolver.solver.explanations
[ERROR] diagnostic: /home/ezulkosk/idea/choco-graph-fork/src/main/java/org/chocosolver/solver/variables/GraphVar.java:207: error: cannot find symbol
    public void explain(ExplanationEngine xengine, VariableState what, Explanation to) {
                                                   ^
  symbol:   class VariableState
  location: class org.chocosolver.solver.variables.GraphVar<E>
[ERROR] diagnostic: /home/ezulkosk/idea/choco-graph-fork/src/main/java/org/chocosolver/solver/variables/GraphVar.java:212: error: cannot find symbol
    public void explain(ExplanationEngine xengine, VariableState what, int val, Explanation to) {
                                                   ^
  symbol:   class VariableState
  location: class org.chocosolver.solver.variables.GraphVar<E>
[ERROR] diagnostic: /home/ezulkosk/idea/choco-graph-fork/src/main/java/org/chocosolver/solver/search/GraphDecision.java:31: error: cannot find symbol
import org.chocosolver.solver.explanations.Deduction;
                                          ^
  symbol:   class Deduction

**Comment by cprudhom** [comment]
Hi,

The current version of the choco-graph has been designed on the top of choco-3.3.0.
Since then, the code of choco3 has been modified in such way that there can't be backward compatibility, and that's why you encountered errors moving to the last (under development) version of choco3.
The code of choco-graph has to be updated in consequence, in the meantime, you'll have to use choco-3.3.0.
By the way, why do you want to use choco-3.3.2 ? 

Hope it helps, 
CP

**Comment by ezulkosk** [comment]
Got it, thanks for your help. I'm working on the Clafer project (in collaboration with Jimmy Liang), which has a large codebase dependent on choco-3.3.2. We are in the midst of adding some graph constraints to the language.

**Comment by cprudhom** [comment]
Hi,

I've deployed choco-solver-3.2.2-SNAPSHOT on sonatype snapshots repo, and udpated choco-graph code in consequence (no release though) and pushed it into the develop branch.
That should be OK now.

Hope it helps,
CP
