### ISSUE TITLE
(SNAPSHOT) release for 4.0.0.a?

### ISSUE THREAD

**Issue by myedibleenso** [chocoteam/choco-graph#8]
Hi!  This is not really a bug report, but more a question regarding the readme:

> This extension of Choco Solver works with choco-solver-4.0.0-SNAPSHOT (not released yet, to be compiled from github sources) and associated dependencies. It requires JDK 1.8+

I noticed that `choco-solver` has a `4.0.0-SNAPSHOT` release:

https://oss.sonatype.org/content/repositories/snapshots/org/choco-solver/choco-solver/4.0.0-SNAPSHOT/

With that dependency satisfied, would you consider releasing `4.0.0.a` or a compatible SNAPSHOT of `choco-graph` to https://oss.sonatype.org/content/repositories/snapshots/org/choco-solver/choco-graph?

**Comment by jgFages** [comment]
Hi! Thank you, I have updated the readme (and the technical documentation). 
I believe we will release it on sonatype too, but I do not know when exactly.

**Comment by malbarbo** [comment]
Hello, any idea when choco-graph 4.0.4 will be published?

**Comment by jgFages** [comment]
Well... it is already!
https://github.com/chocoteam/choco-graph/releases

**Comment by malbarbo** [comment]
Ow, I see.

But it seems that is is [not available](https://mvnrepository.com/artifact/org.choco-solver/choco-graph) in maven repositories.

**Comment by jgFages** [comment]
Done!
see https://mvnrepository.com/artifact/org.choco-solver/choco-graph
Note that version numbers have changed (use choco-graph-4.1.1, to be used with choco-solver-4.0.4)

**Comment by malbarbo** [comment]
Thank you!
